Add #102 - Graph Component Raise Event
innovolve-ai/typerefinery pull request #106
Opened 2022-05-11 05:19 UTC by ankitvats1

- Added click events on graph node.
- Displayed node properties on Properties Component.
- Added unit test for graphs.

2022-05-11 08:51 UTC, rohitgupta274509 approved these changes

2022-05-12 04:57 UTC, Rahul139-stack approved these changes

2022-05-12 05:23 UTC, Shivam-apna approved these changes

2022-05-12 06:48 UTC, wildone requested changes

2022-05-12 06:48 UTC, wildone commented on src/components/Project/ContentTab/index.vue
> +            <!-- <Button
can we add //todo:?

2022-05-12 11:23 UTC, ankitvats1 commented on src/components/Project/ContentTab/index.vue
> +            <!-- <Button
Added

2022-05-13 06:03 UTC, wildone approved these changes

2022-05-13 06:10 UTC, wildone approved these changes

2022-05-13 06:10 UTC, merged