added #89 populate project tree using new project
innovolve-ai/typerefinery pull request #152
Opened 2022-06-09 06:49 UTC by rohitgupta274509

please review and approve it.

2022-06-09 06:59 UTC, ankitvats1 approved these changes

2022-06-09 08:18 UTC, Shivam-apna submitted a review, later dismissed

2022-06-09 14:22 UTC, wildone requested changes

2022-06-09 14:22 UTC, wildone commented on src/components/Dialog/Projects.vue
> +          >{{ v$.name.required.$message.replace("Value", "Name") }}</small
whats this for?

2022-06-09 14:22 UTC, wildone commented on src/components/Dialog/Projects.vue
> +        const data = {
is this coming from localstore?

2022-06-09 15:18 UTC, rohitgupta274509 commented on src/components/Dialog/Projects.vue
> +        const data = {
this is coming from store.

2022-06-10 05:24 UTC, sanjayaapna approved these changes

2022-06-14 22:15 UTC, wildone approved these changes

2022-06-14 22:15 UTC, merged