fixed menu buttons style.
innovolve-ai/typerefinery pull request #354
Opened 2022-10-19 13:22 UTC by Shivam-apna

Please review and approve it.

2022-10-26 11:54 UTC, ankitvats1 requested changes

2022-10-26 11:54 UTC, ankitvats1 commented on src/components/Loader/loaderMenu.vue
> +  <div class="menu-bar" :class="{ focus: focus }">
Remove focus.

2022-10-26 11:54 UTC, ankitvats1 commented on src/components/Loader/loaderMenu.vue
> +      const theme = settingsModule?.data.theme || "light"
Remove this.

2022-10-26 11:54 UTC, ankitvats1 commented
Update your branch.

2022-10-31 05:13 UTC, brsmxq commented
@Shivam-apna  can you please review this?

2022-10-31 05:20 UTC, merged